dataset: cais/hle

provider: vllm # [vllm]

base_url: http://localhost:8000/v1

model: microsoft/Phi-4-reasoning-plus
# model: Qwen/Qwen3-32B
max_completion_tokens: 100000
reasoning: true

# sample with multimodal is 2500, so text-only sample is about 2400
num_workers: 2500
max_samples: 2400

judge: o3-mini-2025-01-31

# 記載されたカテゴリのみ評価
# 一例
# category_filter:
#   - "Math"

category_filter:
  - "Biology/Medicine"
  - "Computer Science/AI"
  - "Other"
  - "Humanities/Social Science"
  - "Physics"
  - "Chemistry"


# category_filter: null
